apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsubmvcsample
  #namespace: default
  labels:
    app: pubsubmvcsample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsubmvcsample
  template:
    metadata:
      labels:
        app: pubsubmvcsample
        service: pubsubmvcsample
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pubsubmvcsample"
        #dapr.io/app-port: "80"
        dapr.io/log-level: "info"
        dapr.io/config: "tracing"
        #dapr.io/sidecar-liveness-probe-period-seconds: "20"
        #dapr.io/sidecar-readiness-probe-period-seconds: "20"
    spec:
      containers:
      - name: pubsubmvcsample
        image: ben2code/pubsubmvcsample:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: pubsubmvcsample
  labels:
    app: pubsubmvcsample
    service: pubsubmvcsample
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: pubsubmvcsample